types = [ "Amendment to Law",
        "API",
        "App",
        "Appointment",
        "Community - Data",
        "Community - Website",
        "Contest",
        "Copyright",
        "Event",
        "Executive Order",
        "Federal Law",
        "Hearing",
        "Law",
        "Local Law",
        "Meeting",
        "Policy",
        "Publication",
        "Software",
        "Website"]